window.GEI_RESEARCH = {
  schemaVersion: "0.5.0",
  records: [
    {
      id: "GEI-PAP-001",
      type: "paper",
      title: "Genesis Engineered Interpretations: A Systems-Interpretation Framework",
      slug: "genesis-engineered-interpretations-systems-framework",
      status: "working-paper",
      version: "0.1.0",
      author: "Genesis Engineered Interpretations",
      abstract: "A framework record for studying Genesis through an engineering and systems-interpretation lens. The record separates textual observations, interpretive proposals, evidence, and conclusions so that each claim can be revised or challenged independently.",
      keywords: ["Genesis", "systems interpretation", "engineering", "textual analysis"],
      sources: ["Genesis 1:1–31 (KJV)"],
      evidence: ["GEI textual observation set", "GEI hydraulic-system mapping"],
      claims: ["Genesis 1 can be examined as a sequence of ordered transformations.", "Engineering analogies can be documented as interpretations rather than presented as established historical facts."],
      related: ["GEI-EVD-001", "GEI-SRC-001", "GEI-TAX-001"],
      provenance: {recordedBy:"GEI Research System", method:"Version-controlled research record", recordedAt:"2026-09-08", evidenceRefs:["GEI-ERA V0.5"]}
    },
    {
      id: "GEI-WP-001",
      type: "working-paper",
      title: "GEI Research Decision & Outcome Log",
      slug: "gei-research-decision-outcome-log",
      status: "active",
      version: "0.1.0",
      author: "Genesis Engineered Interpretations",
      abstract: "A living record for research questions, decisions, evidence reviewed, outcomes, uncertainty, and subsequent revisions.",
      keywords: ["research decisions", "outcomes", "audit trail", "revision"],
      sources: ["GEI Research Architecture"],
      evidence: ["Research decision records"],
      claims: ["Research decisions should remain traceable to the evidence and reasoning available when the decision was made."],
      related: ["GEI-EVD-001", "GEI-AUD-001"],
      provenance: {recordedBy:"GEI Research System", method:"Structured decision record", recordedAt:"2026-09-08", evidenceRefs:["GEI-RES-001"]}
    },
    {
      id: "GEI-EVD-001",
      type: "evidence",
      title: "Genesis 1:1–5 Textual Observation Set",
      slug: "genesis-1-1-5-textual-observation-set",
      status: "active",
      version: "0.1.0",
      author: "Genesis Engineered Interpretations",
      abstract: "A source-anchored observation record for Genesis 1:1–5 (KJV), intended to distinguish what the text says from subsequent interpretation.",
      keywords: ["KJV", "Genesis 1", "observation", "text"],
      sources: ["Genesis 1:1–5 (KJV)"],
      evidence: ["Verse and punctuation observations"],
      claims: ["The observation layer should precede the interpretive layer in the GEI research workflow."],
      related: ["GEI-PAP-001", "GEI-SRC-001"],
      provenance: {recordedBy:"GEI Research System", method:"Source-anchored observation", recordedAt:"2026-09-08", evidenceRefs:["Genesis 1:1–5 (KJV)"]}
    },
    {
      id: "GEI-SRC-001",
      type: "source",
      title: "Genesis 1:1–31 (KJV)",
      slug: "genesis-1-1-31-kjv",
      status: "active",
      version: "1.0.0",
      author: "Source text",
      abstract: "Primary textual source used by GEI for the Genesis Chapter 1 research corpus.",
      keywords: ["KJV", "Genesis", "primary source"],
      sources: ["King James Version Bible"],
      evidence: ["Genesis 1:1–31"],
      claims: [],
      related: ["GEI-EVD-001", "GEI-TAX-001"],
      provenance: {recordedBy:"GEI Research System", method:"Source registration", recordedAt:"2026-09-08", evidenceRefs:["Genesis 1:1–31 (KJV)"]}
    },
    {
      id: "GEI-CHR-001",
      type: "chronology",
      title: "GEI Genesis Chapter 1 Six-Day Research Chronology",
      slug: "gei-genesis-chapter-1-six-day-chronology",
      status: "working-model",
      version: "0.1.0",
      author: "Genesis Engineered Interpretations",
      abstract: "A chronological research model organizing Genesis Chapter 1 into six interpretive stages. It is explicitly a GEI model, not a claim that the source text itself uses engineering terminology.",
      keywords: ["chronology", "six days", "Genesis 1", "research model"],
      sources: ["Genesis 1:1–31 (KJV)"],
      evidence: ["GEI chronology mapping"],
      claims: ["GEI organizes Chapter 1 into six interpretive stages for analysis."],
      related: ["GEI-PAP-001", "GEI-TAX-001"],
      provenance: {recordedBy:"GEI Research System", method:"Interpretive chronology model", recordedAt:"2026-09-08", evidenceRefs:["Genesis 1:1–31 (KJV)"]}
    },
    {
      id: "GEI-TAX-001",
      type: "taxonomy",
      title: "GEI Master Chronology & Taxonomy — Genesis 1",
      slug: "gei-master-chronology-taxonomy-genesis-1",
      status: "working-model",
      version: "0.1.0",
      author: "Genesis Engineered Interpretations",
      abstract: "A controlled vocabulary for organizing GEI observations, interpretations, systems, sources, and research records around Genesis Chapter 1.",
      keywords: ["taxonomy", "controlled vocabulary", "GEI", "Genesis 1"],
      sources: ["GEI research architecture", "Genesis 1:1–31 (KJV)"],
      evidence: ["GEI terminology records"],
      claims: ["A controlled vocabulary can improve consistency across GEI research records."],
      related: ["GEI-CHR-001", "GEI-SRC-001"],
      provenance: {recordedBy:"GEI Research System", method:"Taxonomy design", recordedAt:"2026-09-08", evidenceRefs:["GEI Master Chronology & Taxonomy"]}
    },
    {
      id: "GEI-AUD-001",
      type: "audit",
      title: "GEI Research Audit Trail",
      slug: "gei-research-audit-trail",
      status: "active",
      version: "0.1.0",
      author: "Genesis Engineered Interpretations",
      abstract: "A research audit structure for recording record creation, revisions, evidence changes, review events, and decision outcomes.",
      keywords: ["audit trail", "provenance", "review", "version control"],
      sources: ["GEI Research Architecture"],
      evidence: ["Git history", "Research record metadata"],
      claims: ["Research records should retain enough provenance to reconstruct how a conclusion or interpretation changed over time."],
      related: ["GEI-WP-001", "GEI-EVD-001"],
      provenance: {recordedBy:"GEI Research System", method:"Audit architecture", recordedAt:"2026-09-08", evidenceRefs:["Git version history"]}
    }
  ],
  reviewStates: ["unreviewed", "in-review", "reviewed", "revision-requested", "accepted", "archived"]
};
